### ISSUE TITLE
[Missing] 关闭fill set产生的方块更新

### ISSUE THREAD

**Issue by Monoryxiaole** [LeavesMC/Documentation#23] opened 2024-08-11 04:23 UTC
### What type of documentation are we missing?

Project

### What should be added?

`/leaves` 命令

- [ ]  关闭fill方块更新
- [ ]  关闭set方块更新
- [ ]  关闭全局方块更新

**Comment by LittleChest** [comment] 2024-08-11 04:42
甚至把tasks都写好了（

**Comment by LittleChest** [comment] 2024-08-13 02:21
此存储库为 LeavesMC 文档站，不接受 Leaves 核心的功能请求，请转到 LeavesMC/Leaves

**Comment by LittleChest** [comment] 2024-08-15 04:06
Duplicate of #10

**Closed by LittleChest** 2024-08-15 04:06 UTC
Labels: missing
